BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `catInfo` (
	`id`	integer PRIMARY KEY AUTOINCREMENT,
	`catName`	TEXT,
	`catDetails`	TEXT
);
INSERT INTO `catInfo` VALUES (1,'Abyssinian ','The Abyssinian cat as it is known today was bred in Great Britain. The name ''Abyssinian'' refers to Ethiopia, in reference to widely-spread stories of British soldiers deployed to North Africa in the nineteenth century returning home with kittens purchased from local traders.');
INSERT INTO `catInfo` VALUES (2,'Aegean','The Aegean cat (Greek: γάτα του Αιγαίου gáta tou Aigaíou) is a naturally occurring landrace of domestic cat originating from the Cycladic Islands of Greece. It is considered a natural cat, developing without human interference.[1] Development of the Aegean cat as a formal breed began in the early 1990s by breeders in the fledgling Greek cat fancy, but the variety has yet to be recognized by any major fancier and breeder organization. It is considered to be the only native Greek variety of cat.');
INSERT INTO `catInfo` VALUES (3,'American Curl','The American Curl is a breed of cat characterized by its unusual ears, which curl back from the face toward the center of the back of the skull. An American Curl''s ears should be handled carefully because rough handling may damage the cartilage in the ear. The breed originated in Lakewood, California, as the result of a spontaneous mutation.');
INSERT INTO `catInfo` VALUES (4,'American Bobtail','The American Bobtail is an uncommon breed of domestic cat which was developed in the late 1960s.[1] It is most notable for its stubby "bobbed" tail about one-third to one-half the length of a normal cat''s tail. This is the result of a cat body type genetic mutation affecting the tail development, similar to that of a Manx cat.[1] The breed is not related to the Japanese Bobtail despite the similar name and physical type—the breeding programs are entirely unrelated, and the genetic mutation causing the bobbed tail are known to be different because the mutation causing the American Bobtail''s tail is dominant, whereas the Japanese Bobtail tail mutation is recessive.[2]

American Bobtails are a very sturdy breed, with both short- and long-haired coats. Their coat is shaggy rather than dense or fluffy. They can have any color of eyes and coat, with a strong emphasis on the "wild" tabby appearance in show animals');
INSERT INTO `catInfo` VALUES (5,'American Shorthair','The American Shorthair (ASH) is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats.[1] According to the Cat Fancier''s Association, in 2012, it was the seventh most popular pedigreed cat in the United States.');
INSERT INTO `catInfo` VALUES (6,'Australian Mist','The Australian Mist (formerly known as the Spotted Mist) is a breed of cat developed in Australia.This breed was developed by Truda Straede in Australia beginning in 1975. The breed was developed by crossing the Burmese, Abyssinian, and miscellaneous domestic short-haired cats to create a short-haired cat with a spotted coat. The name was changed from "Spotted Mist" to "Australian Mist" in 1998, when cats with marbled coats, rather than spots, were accepted as part of the breed.');
INSERT INTO `catInfo` VALUES (7,'Balinese','The Balinese is a long-haired breed of domestic cat with Siamese-style point coloration and sapphire-blue eyes. The Balinese is also known as the purebred long-haired Siamese, since it originated as a natural mutation of that breed[1], and hence is essentially the same cat with a medium-length silky coat and a distinctively plumed tail.

As is the case with their short-haired counterparts, a genetic distinction is made between traditional or "old-style" and modern body types. In the American standard, color variants derived from the Colorpoint Shorthair are further considered a separate breed, known as the Javanese. There is no particular connection between these cats and the Indonesian islands of Bali and Java, from which they derive their names.Like their Siamese ancestors, Balinese are sociable, vocal, playful and inquisitive, and considered an intelligent breed.');
INSERT INTO `catInfo` VALUES (8,'Bambino','The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. However, some Bambino cats do have fur.The first litter of Bambino kittens was registered in 2005. It was registered by TICA in 2005 as an experimental breed, Experimental Bambino, in 2006.[2] "Bambino" means "baby" in Italian, as to the cats appearance of making it look like a kitten.

The Bambino has short legs it inherits from the Munchkin, and huge upright ears. It has the hairlessness of the Sphynx, with skin of white or pink. With no fur to absorb the cat''s natural oils, the Bambino needs regular bathing with water and mild soap. The Bambino''s hairless skin means that the cat is vulnerable to cold, strong sunshine and skin injury.');
INSERT INTO `catInfo` VALUES (9,'Birman','The Birman, also called the "Sacred Cat of Burma",is a domestic cat breed. The Birman is a long-haired, color-pointed cat distinguished by a silky coat, deep blue eyes, and contrasting white "gloves" or "socks" on each paw.
The breed name is derived from Birmanie, the French form of Burma. The Birman breed was first recognized in France by the Cat Club de France in 1925, then in England by the Governing Council of the Cat Fancy (GCCF) in 1966 and in United States by the Cat Fanciers'' Association (CFA) in 1967. It is also recognized by the Canadian Cat Association (CCA) and the International Cat Association (TICA) in 1979.');
INSERT INTO `catInfo` VALUES (10,'British Shorthair','The British Shorthair is the pedigreed version of the traditional British domestic cat, with a distinctively chunky body, dense coat and broad face. The most familiar color variant is the "British Blue", a solid blue-gray with copper eyes, medium tail, but the breed has also been developed in a wide range of other colours and patterns, including tabby and colorpoint.

It is one of the most ancient cat breeds known, probably originating from European domestic cats imported into Britain by the invading Romans in the first century AD. In modern times it remains the most popular pedigreed breed in its native country, as registered by the UK''s Governing Council of the Cat Fancy (GCCF).

The breed''s good-natured appearance and relatively calm temperament make it a frequent media star, notably as the inspiration for John Tenniel''s famous illustration of the Cheshire Cat from Alice in Wonderland. The Cat Fanciers'' Association profile reads: "When gracelessness is observed, the British Shorthair is duly embarrassed, quickly recovering with a ''Cheshire cat smile''”');
INSERT INTO `catInfo` VALUES (11,'American Wirehair','The American Wirehair is a breed of domestic cat originating in upstate New York. As of 2003, though the breed is well-known, it is ranked as the most rare of the 41 Cat Fanciers'' Association breeds, with only 22 registered, down from 39 in 2002.American Wirehairs are similar to American Shorthairs, with the exception of a springy, wiry coat, including ear fur, and whiskers.[3] This coat is similar to the wire coats of some dog breeds, such as terriers. Their fur requires little grooming, although lighter cats may require sunblock. Wirehairs are of a moderate, sturdy build, with round heads, high cheekbones, and a pronounced muzzle.[4] Females are generally smaller than males.[1] American Wirehairs display the full spectrum of possible cat coat colors, although Himalayan, Chocolate and Lilac are not accepted for competition. The Wirehair coat trait is dominant, so any breeding between a Wirehair and another cat can produce wired kittens. Wirehairs have golden eyes, except for some white ones that have blue or amber eyes.');
INSERT INTO `catInfo` VALUES (12,'Asian Semi-longhair','The Asian Semi-Longhair is a cat breed similar to the Asian Shorthair except it has semi-long fur. The breed is also known by the name Tiffanie or Tiffany. It is recognized in any of the Asian Shorthair or Burmese colors and patterns. Like the Asian Shorthair, the breed was developed in Britain and is not currently recognized by any U.S. Registries. It has full recognition in the GCCF.[1] It is related to, and in some registries distinct from, the Chantilly-Tiffany or Foreign Longhair, the North American variant.');
CREATE TABLE IF NOT EXISTS `android_metadata` (
	`locale`	TEXT
);
INSERT INTO `android_metadata` VALUES ('en_US');
COMMIT;
