BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `catInfo` (
	`id`	integer PRIMARY KEY AUTOINCREMENT,
	`catName`	TEXT,
	`catDetails`	TEXT
);
INSERT INTO `catInfo` VALUES (1,'Abyssinian ','The Abyssinian cat as it is known today was bred in Great Britain. The name ''Abyssinian'' refers to Ethiopia, in reference to widely-spread stories of British soldiers deployed to North Africa in the nineteenth century returning home with kittens purchased from local traders.');
INSERT INTO `catInfo` VALUES (2,'Aegean','The Aegean cat (Greek: γάτα του Αιγαίου gáta tou Aigaíou) is a naturally occurring landrace of domestic cat originating from the Cycladic Islands of Greece. It is considered a natural cat, developing without human interference.[1] Development of the Aegean cat as a formal breed began in the early 1990s by breeders in the fledgling Greek cat fancy, but the variety has yet to be recognized by any major fancier and breeder organization. It is considered to be the only native Greek variety of cat.');
INSERT INTO `catInfo` VALUES (3,'American Curl','The American Curl is a breed of cat characterized by its unusual ears, which curl back from the face toward the center of the back of the skull. An American Curl''s ears should be handled carefully because rough handling may damage the cartilage in the ear. The breed originated in Lakewood, California, as the result of a spontaneous mutation.');
INSERT INTO `catInfo` VALUES (4,'American Bobtail','The American Bobtail is an uncommon breed of domestic cat which was developed in the late 1960s.[1] It is most notable for its stubby "bobbed" tail about one-third to one-half the length of a normal cat''s tail. This is the result of a cat body type genetic mutation affecting the tail development, similar to that of a Manx cat.[1] The breed is not related to the Japanese Bobtail despite the similar name and physical type—the breeding programs are entirely unrelated, and the genetic mutation causing the bobbed tail are known to be different because the mutation causing the American Bobtail''s tail is dominant, whereas the Japanese Bobtail tail mutation is recessive.[2]

American Bobtails are a very sturdy breed, with both short- and long-haired coats. Their coat is shaggy rather than dense or fluffy. They can have any color of eyes and coat, with a strong emphasis on the "wild" tabby appearance in show animals');
INSERT INTO `catInfo` VALUES (5,'American Shorthair','The American Shorthair (ASH) is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats.[1] According to the Cat Fancier''s Association, in 2012, it was the seventh most popular pedigreed cat in the United States.');
INSERT INTO `catInfo` VALUES (6,'Australian Mist','The Australian Mist (formerly known as the Spotted Mist) is a breed of cat developed in Australia.This breed was developed by Truda Straede in Australia beginning in 1975. The breed was developed by crossing the Burmese, Abyssinian, and miscellaneous domestic short-haired cats to create a short-haired cat with a spotted coat. The name was changed from "Spotted Mist" to "Australian Mist" in 1998, when cats with marbled coats, rather than spots, were accepted as part of the breed.');
INSERT INTO `catInfo` VALUES (7,'American Wirehair','The American Wirehair is a breed of domestic cat originating in upstate New York. As of 2003, though the breed is well-known, it is ranked as the most rare of the 41 Cat Fanciers'' Association breeds, with only 22 registered, down from 39 in 2002.American Wirehairs are similar to American Shorthairs, with the exception of a springy, wiry coat, including ear fur, and whiskers.[3] This coat is similar to the wire coats of some dog breeds, such as terriers. Their fur requires little grooming, although lighter cats may require sunblock. Wirehairs are of a moderate, sturdy build, with round heads, high cheekbones, and a pronounced muzzle.[4] Females are generally smaller than males.[1] American Wirehairs display the full spectrum of possible cat coat colors, although Himalayan, Chocolate and Lilac are not accepted for competition. The Wirehair coat trait is dominant, so any breeding between a Wirehair and another cat can produce wired kittens. Wirehairs have golden eyes, except for some white ones that have blue or amber eyes.');
INSERT INTO `catInfo` VALUES (8,'Aphrodite Giant','The Cyprus cats are grouped into two subspecies namely Aphrodite Giant  and Saint Helen Cat. On 1st July 2012, the Aphrodite cat became a fully recognised breed of the World Cat Federation. The most influential period for the Cyprus cat’s development occurred in 328 AD when two boatloads of cats were sent to the island from Egypt and Palestine by St Helena. This was done to combat the infestation of snakes on the island following a drought lasting 37 years. The cats were able to breed for 12 hundred years with little outside influence; this has resulted in a breed of cat which is unique, robust, and extremely healthy.
Aphrodites are strong, lively, very affectionate and active cats. They love to play and often develop very close relationships with one particular care giver, rather as dogs do.');
INSERT INTO `catInfo` VALUES (9,'Arabian Mau','The Arabian Mau is a formal breed of domestic cat, originated from the desert cat, a short-haired landrace native to the desert of the Arabian Peninsula. It lives there in the streets and has adapted very well to the extreme climate. The Arabian Mau is recognized as a formal breed by few fancier and breeder organization and cat registry, World Cat Federation (WCF) and Emirates Feline Federation (EFF). Based on one landrace, the Arabian Mau is a natural breed.
It is medium in size, with a body structure that is rather large and firm, not particularly slender, and with well developed musculature. The legs are comparatively long, with oval paws.');
INSERT INTO `catInfo` VALUES (10,'Asian','The Asian, also known as the Malayan, is a cat breed similar to the Burmese but in a range of different coat colours and patterns.[1] Long-haired Asians of all varieties are called Tiffanies. Asians are grouped in the foreign section at cat shows.
The breed was developed in Britain, starting with a litter of kittens bred in 1981 by Baroness Miranda von Kirchberg.
');
INSERT INTO `catInfo` VALUES (11,'Asian Semi-longhair','The Asian Semi-Longhair is a cat breed similar to the Asian Shorthair except it has semi-long fur. The breed is also known by the name Tiffanie or Tiffany. It is recognized in any of the Asian Shorthair or Burmese colors and patterns. Like the Asian Shorthair, the breed was developed in Britain and is not currently recognized by any U.S. Registries. It has full recognition in the GCCF.[1] It is related to, and in some registries distinct from, the Chantilly-Tiffany or Foreign Longhair, the North American variant.');
INSERT INTO `catInfo` VALUES (12,'Balinese','The Balinese is a long-haired breed of domestic cat with Siamese-style point coloration and sapphire-blue eyes. The Balinese is also known as the purebred long-haired Siamese, since it originated as a natural mutation of that breed and hence is essentially the same cat with a medium-length silky coat and a distinctively plumed tail.
As is the case with their short-haired counterparts, a genetic distinction is made between traditional or "old-style" and modern body types. In the American standard, color variants derived from the Colorpoint Shorthair are further considered a separate breed, known as the Javanese. There is no particular connection between these cats and the Indonesian islands of Bali and Java, from which they derive their names.

Like their Siamese ancestors, Balinese are sociable, vocal, playful and inquisitive, and an intelligent breed.');
INSERT INTO `catInfo` VALUES (13,'Bambino','The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. However, some Bambino cats do have fur.
The wrinkled hairless appearance and short legs are the breed''s two most distinctive features, though they can be coated, this however is referred to as a "coated bambino". The back legs can be slightly longer than the front legs. The body is medium to long, with a broad chest and a well-rounded abdomen. Boning is medium. The whippy tail is in good proportion to the rest of the body. Some Bambinos can have a "lion tail"—a puff of hair on the tail tip. The head is a modified wedge with rounded lines, slightly longer than wide. As well as in the Sphynx, the cheekbones and whisker pads are very prominent. The whiskers are sparse and short. The chin is firm. The eyes are large, rounded, and wide spaced. The large ears are set upright, neither too low nor too high. The cat''s size and unique physical qualities do not hamper its movements. The weight is 5 to 9 pounds.');
INSERT INTO `catInfo` VALUES (14,'Bengal','The Bengal is a domestic cat breed developed to look like exotic jungle cats such as leopards, ocelots, margays and clouded leopards. Bengal cats were developed by selective breeding from hybrids of the Asian leopard cat, Prionailurus bengalensis bengalensis, with domestic cat, backcrossed to domestic cats, with the goal of creating a confident, healthy, and friendly cat with a highly contrasted and vividly marked coat.
The name "Bengal cat" was derived from the taxonomic name of the Asian leopard cat (P. b. bengalensis). They have a "wild" appearance with large spots/rosettes/arrowheads, and a light/white belly, and a body structure reminiscent of the Asian leopard cat.[2] Bengals are an intelligent and active breed, and are known for being especially vocal and friendly.[3] Once separated by at least four generations from the original Asian leopard cat – domestic cat crossing, the breed''s temperament resembles that of a domestic cat.[2]

Bengal cats are generally a bright orange to light brown colour, although pale or off-white "snow" Bengals also exist, and are popular among owners.');
INSERT INTO `catInfo` VALUES (15,'Birman','The Birman, also called the "Sacred Cat of Burma",[1] is a domestic cat breed. The Birman is a long-haired, color-pointed cat distinguished by a silky coat, deep blue eyes, and contrasting white "gloves" or "socks" on each paw.

The breed name is derived from Birmanie, the French form of Burma. The Birman breed was first recognized in France by the Cat Club de France in 1925, then in England by the Governing Council of the Cat Fancy[2] (GCCF) in 1966 and in United States by the Cat Fanciers'' Association[1] (CFA) in 1967. It is also recognized by the Canadian Cat Association (CCA) and the International Cat Association');
INSERT INTO `catInfo` VALUES (16,'Bombay','The Bombay cat is a type of short-haired cat developed by breeding sable Burmese and black American Shorthair cats, to produce a cat of mostly Burmese type, but with a sleek, panther-like black coat. Bombay is the name given to black cats of the Asian group.[1] Bombay cat is also called ''mini-panther'' and ''black Burmese''.
The Bombay is a shorthair breed of domestic cat, closely related to the Burmese. The Bombay has a black coat, black toes, and black nose, and copper or green eyes. The close-lying, sleek and glossy black coat is generally coloured to the roots, with little or no paling.

The Bombay has a medium body build that is muscular. Their weight is usually six to twelve pounds (~2.5–5.4 kg) with males typically being heavier than females.');
INSERT INTO `catInfo` VALUES (17,'Brazilian Shorthair','The Brazilian Shorthair is a medium-sized cat of great agility. The breed can be distinguished from the American Shorthair by its sleek and elegant appearance. Yet cats of the breed are not as thin as the Siamese. The coat is short and close to the skin and comes in a wide variety of colors and patterns. The space between the eyes should be equal to the size of one eye. Brazilian Shorthairs have dramatically expressive eyes. They are longer than they are tall. Males have bigger heads than females.

The Brazilian Shorthair Cat had its beginning when the engineer Paulo Samuel Ruschi,[citation needed] a cat breeder and founder of the first Cat Federation in Brazil and the first Cat Club in Rio de Janeiro,[citation needed] had the idea to transform certain cats found in the streets of Brazil into a purebred cat. He focused on the Iberian Peninsula cats, brought to Brazil by the Portuguese in their ships around 1500 A.D. From North to South of Brazil, commissions were created by Dr. Paulo Ruschi to study this animal in all of the country''s parks and streets.[citation needed] After long years of experimental breeding program led by traditional breeders, the Brazilian Shorthair was finally approved by the World Cat Federation, with headquarters in Germany, as a Pure Breed cat. Nowadays, the Brazilian Shorthair cat can participate in contests all over the world.');
INSERT INTO `catInfo` VALUES (18,'British Semi-longhair/LongHair','The British Longhair[1] is a medium-sized, semi-long-haired breed of domestic cat, originating in Great Britain.
The British Longhair is a longer-haired development from the longstanding British Shorthair breed. In the mid-20th century, British Shorthairs were interbred with imported long-haired varieties, like the Turkish Angora and what today is called the Traditional Persian, with an aim to producing more stout and round-faced stock, while retaining the short coat. As a result of this hybridization, British catteries have frequently produced (generally unwanted) semi-long-haired specimens among their litters. In more recent years, these have been intentionally bred (often outside the UK) to each other and sometimes to standard British Shorthairs, to establish a consistent, formalized British Longhair breed.');
INSERT INTO `catInfo` VALUES (19,'British Shorthair','The British Shorthair is the pedigreed version of the traditional British domestic cat, with a distinctively chunky body, dense coat and broad face. The most familiar color variant is the "British Blue", a solid blue-gray with copper eyes, medium tail, but the breed has also been developed in a wide range of other colours and patterns, including tabby and colorpoint.

It is one of the most ancient cat breeds known, probably originating from European domestic cats imported into Britain by the invading Romans in the first century AD. In modern times it remains the most popular pedigreed breed in its native country, as registered by the UK''s Governing Council of the Cat Fancy (GCCF).

The breed''s good-natured appearance and relatively calm temperament make it a frequent media star, notably as the inspiration for John Tenniel''s famous illustration of the Cheshire Cat from Alice in Wonderland. The Cat Fanciers'' Association profile reads: "When gracelessness is observed, the British Shorthair is duly embarrassed, quickly recovering with a ''Cheshire cat smile''”');
INSERT INTO `catInfo` VALUES (20,'Burmese cat','The Burmese (Thai: ทองแดง or ศุภลักษณ์, RTGS: Thongdaeng or Supphalak, meaning copper colour) is a breed of domestic cat, originating in Thailand, believed to have its roots near the present Thai-Burma border and developed in the United States and Britain.

Most modern Burmese are descendants of one female cat called Wong Mau, which was brought from Burma to America in 1930 and bred with American Siamese. From there, American and British breeders developed distinctly different Burmese breed standards, which is unusual among pedigreed domestic cats. Most modern cat registries do not formally recognize the two as separate breeds, but those that do refer to the British type as the European Burmese.

Originally, all Burmese cats were dark brown (sable), but are now available in a wide variety of colours; formal recognition of these also varies by standard. Both versions of the breed are known for their uniquely social and playful temperament and persistent vocalisation.');
INSERT INTO `catInfo` VALUES (21,'Burmilla','The Burmilla is a breed of domestic cat which originated in the United Kingdom in 1981. It is a cross between the Chinchilla Persian and Burmese breeds. Standards were produced in 1984, and the breed gained championship status in the United Kingdom in the 1990s.
The Burmilla was born in the United Kingdom. Two cats, a Chinchilla Persian named Sanquist, and Fabergé which was a Brown tortie burmese were both awaiting a partner of their own breed in different rooms. One night the cleaner left the door open. The two cats bred, producing four kittens born in 1981. Thus, a new breed was born.');
INSERT INTO `catInfo` VALUES (22,'California Spangled','The California Spangled is a breed of domestic cat that was bred to resemble spotted wild cats, like the ocelot and leopard. They were originally bred in the 1980s and were only ever a rare breed, with only 58 ever being registered.[1] They were usually expensive, priced between US$800 and $2,500.[2] The popularity of two other spotted cats breeds, the Ocicat and the Bengal, overshadowed their development.

Inspired by the poaching death of a leopard, the anthropologist Louis Leakey motivated Paul Arnold Casey, Jr. of California to breed a domestic cat resembling a small leopard in order to emphasize how important it was to preserve the leopard.

California Spangled cats are a crossbreed of many strains, including the Abyssinian, American Shorthair and British Shorthair. Despite their wild appearance, they are completely domestic.');
INSERT INTO `catInfo` VALUES (23,'Chantilly-Tiffany','The Chantilly-Tiffany or Chantilly/Tiffany, also known as the Chantilly or the Foreign Longhair, is a breed of cat derived mainly from cross-breeding long-haired Asians and Burmese. The breed was originated in North America. This breed is considered distinct from the Asian Semi-longhair breed, the British variant. The Chantilly was thought extinct until the 1960s when two of these cats appeared during an estate sale.
This cat has a semi-foreign body style and a full semi-long coat. The coat is silky, soft and smooth; the lack of undercoat usually makes grooming simpler than that of cats with an undercoat. The Chantilly-Tiffany is slow to mature and usually does not come into its full stature until about two years old. The eye color of the feline intensifies with age. The head should be a broad, modified wedge with gentle curves. It should have a medium length nose and a strong, broad, short, softly squared muzzle and defined but not obvious whisker pads.

The Chantilly-Tiffany originated in a chocolate color, but now is accepted in a range of colors including chocolate, blue, cinnamon, lilac, and fawn. Accepted patterns are solid, mackerel, ticked, and spotted tabby. The color is rich; shading in solids may occur toward the underside. The overall impression of an ideal Chantilly would be a semi-foreign cat of striking appearance resulting from the combination of its rich color and full, silky semi-longhair coat, plumed tail, contrasting neck ruff, and ear furnishings.');
INSERT INTO `catInfo` VALUES (24,'Chartreux','The Chartreux is a rare breed of domestic cat from France and is recognised by a number of registries around the world. The Chartreux is large and muscular (called cobby) with relatively short, fine-boned limbs, and very fast reflexes. They are known for their blue (grey) water-resistant short hair double coats which are often slightly nappy in texture (often showing "breaks" like a sheepskin) and orange- or copper-colored eyes. Chartreux cats are also known for their "smile": due to the structure of their heads and their tapered muzzles, they often appear to be smiling. Chartreux are exceptional hunters and are highly prized by farmers.');
INSERT INTO `catInfo` VALUES (25,'Chausie','The Chausie (/ˈtʃaʊsi/) is a domestic breed of cat that was developed by breeding a few individuals from the nondomestic species jungle cat (Felis chaus) to a far greater number of domestic cats (Felis catus). The Chausie was first recognized as a domestic breed by The International Cat Association (TICA). Within the domestic breeds, the Chausie is categorized as a nondomestic hybrid source breed.[1] Other domestic breeds in this category include the Bengal and the Savannah. Because Chausies are mostly descended from domestic cats, by about the fourth generation they are fully fertile and completely domestic in temperament. Chausies should be tall, long, and lean, with very long legs and medium boning. The torso is deep-chested with flat sides. The ears are broad, tall, and set high on the head, about two fingers apart. The cheekbones are striking—prominent, long, and angular—and the eyes are flattened on top and form a half oval below. The coat is short, and the cats can come in three colors: solid black, black grizzled tabby, and black (brown) ticked tabby. Gold or yellow eye color is preferred, though yellower and lighter shades of green are allowed.');
INSERT INTO `catInfo` VALUES (26,'Colorpoint Shorthair','Colorpoint Shorthairs are a variety of domestic cat. Depending on the cat registry, they may be considered a separate breed of cat, or more often a variant of a pre-existing one, if accepted at all. These cats are distinguished by their conformance to wide range of sixteen different point colors, beyond the four standard Siamese colors. The variety was initially created by crossbreeding Siamese with the American Shorthair – the same mixture that created the Oriental Shorthair, but with different goals. The Colorpoint Shorthair shares the point-coloration pattern with the Siamese, but in the nontraditional colors of red, cream, tortoiseshell, and lynx (tabby) points, and minor variations thereof. In body style, head shape, and other features, it may be intermediate between the two foundation breeds, which show cats leaning toward Siamese traits. Those who favour the Traditional Siamese look may also favour the more moderate-typed Colourpoint Shorthairs that take after their American Shorthair ancestors in shape.

The Cat Fanciers'' Association (CFA) and the World Cat Federation (WCF) are the only major registries that recognize them as a standalone breed. In other registries, they are part of the Siamese or Oriental Shorthair breeds (and may not be accepted as show and breeding quality, depending on what colors the registry permits in these breeds, and whether they permit any outbreeding in the lineage). Because these cats are a crossbreed, various registries are resistant to accepting either as breeds, or as valid Siamese');
INSERT INTO `catInfo` VALUES (27,'Cornish Rex','A Cornish Rex is a breed of domestic cat. The Cornish Rex has no hair except for down. Most breeds of cat have three different types of hair in their coats: the outer fur or "guard hairs", a middle layer called the "awn hair"; and the down hair or undercoat, which is very fine and about 1 cm long. Cornish Rexes only have the undercoat. Cornish Rex are prone to hair loss and many will develop a very thin coat or even go bald over large parts of their body. The curl in Cornish Rex fur is caused by a different mutation and gene than that of the Devon Rex. The breed originated in Cornwall, Great Britain.

The coat of a Cornish Rex is extremely fine and sometimes curly. Their light coat means that they are best suited for indoor living in warm and dry conditions, as they are sensitive to low temperatures. Cornish Rexes like to stay near warm places such as computer monitors, light bulbs, laps and shoulders.

The breed is sometimes referred to as the Greyhound of the cats, because of the sleek appearance and the galloping run characteristic of the breed.[1] These cats tend to stay playful and kittenish throughout their long lives. Some Cornish Rexes like to play fetch, race other pets, or do acrobatic jumps. The Cornish Rex is an adventurous cat and is very intelligent. It can readily adapt to new situations and will explore wherever it can go. The Rex is extremely curious, seeks out the company of people and is friendly towards other companion animals.');
INSERT INTO `catInfo` VALUES (28,'Cymric/Manx Longhair','The Cymric (/ˈkɪmrɪk/ KIM-rik, /ˈkʌm-/ KUM-) is a breed of domestic cat. Some cat registries consider the Cymric simply a semi-long-haired variety of the Manx breed, rather than a separate breed. Except for the length of fur, in all other respects the two varieties are the same, and kittens of either sort may appear in the same litter. The name comes from Cymru (Welsh pronunciation: [ˈkəmrɨ]), the indigenous Welsh name of Wales, though the breed is not associated with Wales, and the name was possibly given as an attempt to provide a "Celtic"-sounding name for the breed. The breed''s Manx bloodline originated in the Isle of Man, though Canada claims to have developed the long-haired variant. The breed is called the Longhair Manx or a similar name by some registries.
The Cymric is a muscular, compact, medium to large cat with a sturdy bone structure, weighing between seven and thirteen pounds. They have a cobby body, and an unusually rounded appearance. Cymrics have large and full eyes and have widely spaced ears. Unlike that of the parent Manx breed, the hair of a Cymric is medium-long, dense and well padded over the main body, adding further to the round appearance. All colours and patterns that are accepted for the Manx are accepted for the Cymric (though exactly which qualify varies by organization).');
INSERT INTO `catInfo` VALUES (29,'Devon Rex','The Devon Rex is a breed of intelligent, short-haired cat that emerged in England during the late 1950s. They are known for their slender bodies, wavy coat, and large ears. This breed of cat is capable of learning difficult tricks but can be difficult to motivate.
The curl in Devon Rex fur is caused by a different mutation and gene than that of the Cornish Rex and German Rex, and breeding of a Devon with either of those cats results in cats without rexed (curled) fur. Devons, which are medium-sized cats, are often called "pixie cats" or "alien cats" because of their unique appearance. Their uncommonly large, slightly rounded ears are set low on the sides of their wide heads, their eyes are large, and their noses are slightly upturned. Unlike most cats, their whiskers are very short and often curled to such an extent that it may appear as if they have no whiskers. Their body type is distinctly lightly built. Their long, sturdy legs are well suited for long leaps, and their toes are unusually large.');
INSERT INTO `catInfo` VALUES (30,'Donskoy/Don Sphynx','The Donskoy is a mostly hairless cat breed of Russian origin. This breed started in 1987 with the discovery of a hairless cat in the Russian city of Rostov-on-Don by cat breeder Elena Kovaleva.[1] It is not related to the better-known mostly hairless breed of cat, the Sphynx, also known as the Canadian Hairless, whose characteristic hair suppression is caused by a recessive gene, whereas the Don hairlessness is caused by a dominant gene.

The Donskoy was first officially recognized by World Cat Federation (WCF) in 1997, and by The International Cat Association (TICA) in 2005. The standard of points describes the cat as being medium-sized and muscular, with large ears, almond shaped eyes and distinctive long, webbed toes. They require frequent grooming, in spite of their lack of coat. Over-bathing can cause the skin to become very oily');
INSERT INTO `catInfo` VALUES (31,'Dragon Li','The Dragon Li (also called Chinese Li Hua, China Li Hua, Li Hua, Li Hua Mau, Li Hua Mao (in Pinyin); Chinese: 貍花貓 or simply Li Mao (Chinese character: 貍貓)) is a Chinese breed of domestic cat originating from nascent Chinese folklore and dynastic culture. The natural breed, based on a native landrace, is recognized as a formal breed by the US-based Cat Fanciers'' Association (CFA) and China''s Cat Aficionado Association .
The Dragon Li displays a unique golden brown, broken mackerel (also known as broken striped) tabby pattern, distinctive ear tipping, large round almond shaped luminescent yellow/green eyes, and a strong full bodied stature reminiscent of its wild nature. The Dragon Li is valued for its unmistakable intelligence, an uncanny cognizance in relation to its surroundings, and its ability to interact perspicuously with humans.');
INSERT INTO `catInfo` VALUES (32,'Dwarf cat/Dwelf','A dwarf cat is any domestic cat which has the condition of dwarfism due to a genetic mutation. Unlike undersized cats of normal proportions, dwarf cats display symptoms of osteochondrodysplasia—genetic disorders of bone and cartilage, typically manifested as noticeably short legs.[1]

Since the mid-twentieth century, cat breeds with embedded dwarfism have been developed for commercial sale. The ethics of their selective breeding is hotly debated, and many countries prohibit it as cruelty to animals.
The term "dwarf cat" is incorrectly applied to cats such as Toy and Teacup Persians which, though small, are breeds of normal feline proportions.[2] True dwarf cats are chondrodysplastic and have much shorter and thicker legs. Typically, half of a dwarf cat litter are non-dwarves born with normal leg length.');
INSERT INTO `catInfo` VALUES (33,'Egyptian Mau','Egyptian Maus are a small- to medium-sized short-haired cat breed. Along with the Bahraini Dilmun cat, they are one of the few naturally spotted breeds of domesticated cat. The spots of the Mau occur on only the tips of the hairs of its coat. It is said to be a rare breed.
The breed conformation is described as "a balance between the compactness of and the slim elegance of a Siamese. Its medium-length body is muscular, with the hind legs longer than the front, giving the Mau the appearance of standing on tiptoes when upright."[1][2]}} The Egyptian Mau is the fastest of the domestic cats,[3] with its longer hind legs, and unique flap of skin extending from the flank to the back knee, providing for greater agility and length of stride. Maus have been clocked running more than 48 km/h (30 mph).[3]

Maus often possess very musical voices. They are known to chirp, chortle, and emit other distinctly unusual vocalizations when stimulated.[4] Another behavior, quite common in happy Maus, has been described as "wiggle-tail." The cat, whether female or male, wiggles and twitches its tail, and appears to be marking territory, also known as spraying, but during this behavior the Mau is not releasing urine. Facial expressions may change according to mood, and eye colour may change from green to turquoise.');
INSERT INTO `catInfo` VALUES (34,'European Shorthair','The European Shorthair, called the European in FIFe and WCF is a breed originating in Europe. The term has also been used as an elaborate way of referring to common domestic cats of Europe, causing some confusion as the pedigree cats of this breed also should resemble the typical domestic cats of Europe. In WCF a similar breed is known as Celtic Shorthair and was at a time considered the same breed, but this breed has some difference from the Europeans, and the WCF now register true Europeans under this breed name instead of under Celtic Shorthair.

The role as the cat breed resembling the original domestic cats of Europe was held until the beginning of the 20th century by the British Shorthair, even though stockier than the majority of common European cats, until 1949 when the European Shorthair was recognized by the Fédération internationale féline (FIFe). The oldest known European Shorthair registered in FIFe was born in 1940, as the origin of the European Shorthair predates the formation of FIFe in 1949. Breed standards describing the European Shorthair as an established breed can be found in different cat books from the 1930s.');
INSERT INTO `catInfo` VALUES (35,'Exotic Shorthair','The Exotic Shorthair is a breed of cat developed to be a short-haired version of the Persian. The Exotic is similar to the Persian in many ways, including temperament and conformation, a flat nose and face with the exceptions of the short dense coat.[1]

In the late 1950s, the Persian was used as an outcross by some American Shorthair breeders. This was done in secret in order to improve their body type, and crosses were also made with the Russian Blue and the Burmese. The crossbreed look gained recognition in the show ring, but unhappy American Shorthair breeders successfully produced a new breed standard that would disqualify American Shorthairs that showed signs of crossbreeding. One American Shorthair breeder who saw the potential of the Persian/American Shorthair cross proposed and eventually managed to get the Cat Fanciers'' Association judge and American Shorthair breeder Jane Martinke to recognize them as a new breed in 1966, under the name Exotic Shorthair. In 1987, the Cat Fanciers'' Association closed the Exotic to shorthair outcrosses, leaving Persian as the only allowable outcross breed.

Because of the regular use of Persian as outcrosses, some Exotics may carry a copy of the recessive longhair gene. When two such cats mate, there is a 1 in 4 chance of each offspring being longhaired. Longhaired Exotics are not considered Persians by the Cat Fanciers'' Association, although The International Cat Association accepts them as Persians. Other associations like the American Cat Fanciers Association register them as a separate Exotic Longhair breed');
INSERT INTO `catInfo` VALUES (36,'Foldex','Foldex cat, also known as the Exotic Fold[1] is a type of cat developed in the Canadian province of Quebec. The physical features of Foldex are a medium-sized cat, rounded face, short legs, and folded ears. The latter are the defining feature of the Foldex. Their eyes are well-rounded and wide open, with pair of ears with small and smooth-edged tips. The coat is varied from long to short hair coat, and naturally dense and soft. They are sweet with charming personalities, active and cheerful cat, which enjoyed being petted');
INSERT INTO `catInfo` VALUES (37,'German Rex','The German Rex is a medium-sized breed with slender legs of a medium length. The head is round with well-developed cheeks and large, open ears. The eyes are of medium size in colours related to the coat colour. The coat is silky and short with a tendency to curl. The whiskers also curl, though less strongly than in the Cornish Rex. They may be nearly straight. All colours of coat, including white, are allowed. The body development is heavier than in the Cornish Rex - more like the European Shorthairs.
A German Rex cat is very friendly and quickly bonds with its owner. It is lively, playful, and intelligent. Its temperament is much the same as a Cornish Rex.');
INSERT INTO `catInfo` VALUES (38,'Havana Brown','The Havana Brown was the result of a planned breeding between Siamese and domestic black cats,[1] by a group of cat fanciers in England, in the 1950s. Early breeders introduced a Siamese type Russian Blue into their breeding. However, using current genetic testing, it is believed that almost none remain in the gene pool.

It has been documented that self-brown cats were shown in Europe in the 1890s, one name given to these was the Swiss Mountain Cat. These disappeared until post-World War II, with the most likely explanation that the Siamese Cat Club of Britain discouraged their breeding.[2] The Swiss Mountain Cat was never used in the breeding programs of the modern Havana Brown. However, they likely share genetics inherited from the Siamese.

The Havana Brown is a well balanced, moderately sized, muscular short-haired cat with a body of average length. Sterilized animals can tend to become larger and somewhat chubby. They are a moderately active breed, compared to other short-hair cat breeds.[1] The coat color must be warm brown, typically reddish-brown, with no obvious tabby markings (note that kittens will always show markings but they resolve as the cat ages and dissolve completely by one year). Whiskers must also be brown and the eye color green. The head should be slightly longer than wide, but should never appear like a wedge. In profile, the nose/muzzle should have a distinct stop and change in direction at the eyes. Paw pads must be pink or rose colored but should never be black. Ears tend to be moderately large. A Havana Brown should have no extreme features; specimens should be attractive and moderate. Males tend to be larger than females and are average in weight compared with other breeds.');
INSERT INTO `catInfo` VALUES (39,'Highlander','The Highlander (also known as the Highlander Shorthair, and originally as the Highland Lynx), is an experimental breed of cat. The unique appearance of the Highlander comes from the deliberate cross between the Desert Lynx and the Jungle Curl breeds, also recently developed. The latter of these has some non-domestic ancestry from two Asian small cat species, the leopard cat and jungle cat, making the Highlander nominally a feline hybrid, though its foundation stock is mostly domestic cat.
The Highlander originated as a crossbreed of the experimental Desert Lynx breed and the Jungle Curl, to add the latter''s curled ears to the former.[1][2][3] As Desert Lynxes, they are bobtailed or short-tailed, have spotted or marbled markings, and resemble the bobcat.[1][4] The Highlander has a long sloping forehead and blunt muzzle with a very wide nose.[4] The eyes are wide-set and the ears are upright with a slight curl and a slight turn in the backward direction.[4] Some have polydactyl paws.[2][3] Highlanders have no known health problems, and are fond of water.[2][3] The body is substantial and very muscular.[3][4] Females can grow to between 10 and 14 pounds, and the males between 15 and 20.[2][3] Despite the "big-cat look", the Highlander is a human-oriented, friendly and playful cat, and very active and confident.[2] The Highlander displays tabby/lynx point or solid point coloration in various colors.');
INSERT INTO `catInfo` VALUES (40,'Himalayan','The Himalayan (a.k.a. Himalayan Persian, or Colourpoint Persian as it is commonly referred to in Europe), is a breed or sub-breed of long-haired cat identical in type to the Persian, with the exception of its blue eyes and its point colouration, which were derived from crossing the Persian with the Siamese.
Like Persians more generally, the Himalayan tends to have a round (cobby) body with short legs, which makes it harder for them to jump as high as other cats do. Since the 1960s, however, some have more of a Siamese-like body,[5] and thus do not have this limitation, but may not be acceptable as show cats, depending on the specific breed standards of the organisation in question.');
INSERT INTO `catInfo` VALUES (41,'Japanese Bobtail','The Japanese Bobtail is a breed of domestic cat with an unusual "bobbed" tail more closely resembling the tail of a rabbit than that of other cats. The variety is native to Japan and Southeast Asia, though it is now found throughout the world. The breed has been known in Japan for centuries, and it frequently appears in traditional folklore and art.

As in most other breeds, Japanese Bobtails may have almost any color (or colors, arranged in any number of patterns). Predominantly-white calicoes (三毛 mi-ke, literally ''triple-hair'') are especially favored by the Japanese and by cat fanciers,[1] and strongly represented in folklore, though other colorations are also accepted by breed standards.');
INSERT INTO `catInfo` VALUES (42,'Javanese','The Javanese is a breed of domestic cat recognized by the Cat Fanciers'' Association as a show cat. It is an oriental-type longhair.[1] The breed was developed in North America and its name is derived from the tradition of naming oriental-type cats after south-east Asian places.
The Javanese cat is from Japan. Genetically they are Japanese long-haired Oriental. The term "Javanese cat" was coined by a Helen Smith of MerryMews Cattery circa 1950.[2][3] It is unknown if she had ever traveled to Indonesia. The name is derived from the tradition of using the names of the countries and islands of south-east Asia for Oriental cat breeds.');
INSERT INTO `catInfo` VALUES (43,'Kurilian Bobtail','The Kurilian Bobtail is a cat breed (or breed group, depending on registry) originating from the Kuril Islands, as well as Sakhalin Island and the Kamchatka peninsula of Russia.[1][2] Short- or long-haired, it has a semi-cobby body type and a distinct short, fluffy tail. The back is slightly arched with hind legs longer than the front, similar to those of the Manx.[2] The breed is also called the Kuril Islands Bobtail, Kuril Bobtail (both often misspelled "Kurile") and Curilsk Bobtail, and may be referred to without "Bobtail". It is sometimes also spelled Kurilean.[3] The original short-haired variant is a natural breed,[2][3] known on the islands for over 200 years.[2] As selectively bred pets, they have been popular in Russia and to some extent other parts of Europe, especially for their rodent-hunting abilities, since the middle of the 20th century,[2] but remain rare in North America[2] as of 2011.

Kurilians are recognized as a breed group of a pair related short- and [semi-]long-haired breeds by The International Cat Association (TICA), which considers them "Advanced New Breeds" ineligible for championship status,[4] as of November 2011) and by the Fédération Internationale Féline (FIFe). The World Cat Federation (WCF) recognizes them as a single breed.[citation needed] As of November 2011, the Cat Fanciers'' Association (CFA) does not recognize the breed at all.
While possibly closely related to the Japanese Bobtail breed – both share the same kind of kinked, short tail, but the Japanese is leaner, more angular and less cobby[1][5] – the Kurilian originated on the opposite side of Eurasia from the similarly named Karelian Bobtail of western Russia and Finland, and is thus unlikely to be a near relative. Genetic studies may eventually demonstrate the breed''s connection to others. Just as the Japanese Bobtail and tailless-to-short-tailed Manx arose independently on islands a world apart, the Kurilian''s bobbed tail may be an isolated spontaneous mutation that became common on the Kuril and Sakhalin islands because of the limited genetic diversity of island biogeography (an example of the founder effect and, at the sub-specific level, of the species-area curve).');
INSERT INTO `catInfo` VALUES (44,'Khao Manee','The Khao Manee cat (Thai: ขาวมณี, ขาวปลอด, RTGS: Khao Mani, Khao Plort, meaning "White Gem"), also known as the Diamond Eye cat,[1] is a rare breed of cat originating in Thailand, which has an ancient ancestry tracing back hundreds of years. They are mentioned in the Tamra Maew, or Cat Book Poems.[2] Khao Manee cats are pure white with a short, smooth, close-lying coat. They can have blue eyes, gold eyes or odd eyes with one of each colour. The odd eyed Khao Manee is the rarest variety. They are muscular, athletic cats of moderate foreign type and are reputed to be active, communicative and intelligent.

Although the breed is well known in its native land it has only recently been adopted by Western cat breeders, gaining "registration only" status from TICA in May 2009. On 3 September 2011, the breed was promoted to "Preliminary New Breed", effective from 1 May 2012, and on 30 August 2013 the breed was promoted to "Advanced New Breed", effective immediately.

On January 24, 2015 the Khaomanee breed was advanced to Championship level in TICA, effective May 1, 2015. (http://www.tica.org/pdf/meetings/winter_2015.pdf, Motion 73)

On 8 September 2010, at the meeting of the GCCF Executive Committee, the Khao Manee was granted breed name in GCCF, and was approved for exhibition only. The Khao Manee Cat Club was granted GCCF pre-affiliation at the Council meeting on 26 October 2011');
INSERT INTO `catInfo` VALUES (45,'Korat','The Korat (Thai: โคราช, มาเลศ, สีสวาด, RTGS: Khorat, Malet, Si sawat) is a silver-tipped blue-grey, short-haired breed of domestic cat with a small to medium build and a low percentage of body fat. Its body is semi-cobby, and unusually heavy for its size. It is an intelligent and playful[1] active cat that forms strong bonds with people. Among the Korat''s distinguishing characteristics is its heart-shaped head and large green eyes.[2]

The Korat is a natural breed, and one of the oldest stable cat breeds. Originating in Phimai, Thailand, it is named after its province of origin, Nakhon Ratchasima Province (typically called "Korat" by the Thai people).[3] In Thailand, the breed is known as Si sawat, meaning "colour of the sawat seed".[1] The Korat is known colloquially as the "good luck cat".[2] Traditionally, they are given in pairs to newlyweds or people who are highly esteemed, for good luck. Until recently, Korats were not sold, but only given as gifts.');
INSERT INTO `catInfo` VALUES (46,'LaPerm','The LaPerm is a recognized breed of cat. A LaPerm''s fur is curly (hence the name "perm"), with the tightest curls being on the belly, throat and base of the ears. LaPerms come in many colors and patterns. LaPerms generally have a very affectionate personality.
The LaPerm is a rex breed which originated in the United States and is now present in many other countries worldwide. The breed is genetically unique and not related to any other rex cat varieties, having a dominant gene causing their curly coats. They have an elegant and athletic build and are affectionate, active and outgoing in character. They are reputed to be hypoallergenic cats, provoking a significantly lower level of allergic response in humans than normal cats. Their most significant feature is their coat, which is made up of soft waves, curls and ringlets, resembling a shaggy perm.');
INSERT INTO `catInfo` VALUES (47,'Lykoi','The Lykoi, also called the Werewolf cat, is a natural mutation from a domestic short-haired cat that has the appearance of a classic Hollywood werewolf, hence its name. The mutation has occurred in domestic cats over the last 20 years. Genetic testing done at UC Davis confirm that the cats do not carry the Sphynx/Devon gene.[1] The Lykoi breed was developed in Vonore, Tennessee. The word lykoi means "wolves" in Greek.
The Lykoi is a partially or almost entirely hairless cat. The hair coat is unique in appearance in that it resembles the coat of an opossum when mostly coated. Standards call for a solid black roan coat, a wedge-shaped head, and a lithe body of solid weight without excessive bulk. Lykoi are said to be friendly and unchallenging in their behavior. They display a high level of affection for their owners.[3]

A unique characteristic of the cat breed is that the Lykoi sheds a lot when older but regrows its hair later in life depending on the season.[4]

The missing coat of the Lykoi''s face gives the breed a werewolfish appearance.');
INSERT INTO `catInfo` VALUES (48,'Maine Coon','The Maine Coon is one of the largest domesticated breeds of cat. It has a distinctive physical appearance and valuable hunting skills. It is one of the oldest natural breeds in North America, specifically native to the state of Maine,[3] where it is the official state cat.

No records of the Maine Coon''s exact origins and date of introduction to the United States exist, so several competing hypotheses have been suggested. The breed was popular in cat shows in the late 19th century, but its existence became threatened when long-haired breeds from overseas were introduced in the early 20th century. The Maine Coon has since made a comeback and is now one of the more popular cat breeds in the world.

The Maine Coon is a large and sociable cat, hence its nickname, "the gentle giant." It is characterized by a prominent ruff along its chest, robust bone structure, triangular body shape, an uneven two layered coat with longer guard hairs with a silky satin under layer undercoat, and a long, bushy tail. The breed''s colors vary widely, with only lilac and chocolate disallowed for pedigree. Reputed for its intelligence and playful, gentle personality, the Maine Coon is often cited as having "dog-like" characteristics.[4][5] Professionals notice certain health problems in the breed including feline hypertrophic cardiomyopathy and hip dysplasia, but reputable breeders use modern screening methods to minimize the frequency of these problems.');
INSERT INTO `catInfo` VALUES (49,'Manx','The Manx cat (/ˈmæŋks/, in earlier times often spelled Manks), is a breed of domestic cat (Felis catus) originating on the Isle of Man, with a naturally occurring mutation that shortens the tail. Many Manx have a small stub of a tail, but Manx cats are best known as being entirely tailless; this is the most distinguishing characteristic of the breed, along with elongated hind legs and a rounded head. Manx cats come in all coat colours and patterns, though all-white specimens are rare, and the coat range of the original stock was more limited. Long-haired variants are sometimes considered a separate breed, the Cymric. Manx are prized as skilled hunters, and thus have often been sought by farmers with rodent problems, and been a preferred ship''s cat breed. They are said to be social, tame and active. An old local term for the cats on their home island is stubbin. Manx have been exhibited in cat shows since the 1800s, with the first known breed standard published in 1903.');
INSERT INTO `catInfo` VALUES (50,'Minskin
','The Minskin is a breed of cat derived from crossing the Munchkin with the Sphynx. In 1998 Paul McSorley began the development of the Minskin in Boston, Massachusetts. Just as the Siamese has color restricted to the points/extremities, Paul McSorley envisioned a cat with short legs and denser fur restricted to the points (fur-points) on the mask, ears, legs and tail, with a noticeably more sparsely coated torso, neck and belly. To accomplish his goal, he crossed his already established Munchkin (show) cats with short legs (short legs are a naturally occurring physical anomaly, a healthy dominant gene) with a full coat of fur. He then introduced and combined ''fuzzy'' Sphynx for the hairless characteristic (hairlessness is a cosmetic anomaly which is a naturally occurring, healthy recessive gene) but with denser fur restricted to the extremities, making for a healthier immune system. When combined, the two healthy mutation genes do not recognised each other and therefore do not cause any detrimental impact. For the appeal of structure, temperament, type and other desired qualities, he also used his International Award Winning Burmese cats and Devon Rex in the development of his Minskin breeding program. The first standard cat that met his goal was "TRT I Am Minskin Hear Me Roar" ''Rory'' was born in July, 2000. By early 2005 about 50 cats meeting the Minskin vision existed and were registered by The International Cat Association (TICA). In 2008 the Minskin became recognized as a Preliminary New Breed (PNB) and is currently in TICA''s program that monitors the development of new breeds and their progress toward achieving the title of Advanced New Breed (ANB). Ultimately, when all necessary requirements are met and with the approval of the BOD, the Minskin breed will advance in TICA with full recognition in the Championship class.');
INSERT INTO `catInfo` VALUES (51,'Munchkin','The Munchkin or ‘’’Sausage Cat’’’ is a relatively new breed of cat characterized by its very short legs, which are caused by a genetic mutation. Much controversy erupted over the breed when it was recognized by The International Cat Association in 1995 with critics voicing concern over potential health and mobility issues.

The name "munchkin" derives from writer L. Frank Baum''s diminutive inhabitants of Munchkin Country, originating in the 1900 novel, The Wonderful Wizard of Oz.
The Munchkin is generally described as a sweet-natured, playful, people-oriented, outgoing and intelligent cat which responds well to being handled.[16] Some sources state that the shortness of their legs does not interfere with their running and leaping abilities,[17] while others state their ability to jump is limited by their condition.[18]

The Munchkin has similar characteristics to normal domestic cats, due to their frequent use as outcrosses. It is a small to medium-sized cat with a moderate body type and medium-plush coat. Male Munchkins typically weigh between 6 and 9 pounds (3–4 kg) and are usually larger than female Munchkins, which typically weigh between 4 and 8 pounds. The hind legs can be slightly longer than the front which creates a slight rise from the shoulder to the rump. The legs of the Munchkin may be slightly bowed, although excessive bowing is a disqualification in the show ring. Cow-hocked legs are also penalized.[4][6]

The Munchkin comes in all coat colors and patterns. It also comes in a long-haired variety, which is shown in a separate Munchkin Longhair category. The short-haired variety has a medium-plush coat while the long-haired has a semi-long silky coat.[4] TICA rules for outcrossing allows the use of any domestic cat that does not already belong to a recognized breed. Similarity to other breeds is grounds for disqualification. Non-standard Munchkins are not allowed to be shown.');
INSERT INTO `catInfo` VALUES (52,'Nebelung','The Nebelung is a rare breed of domestic cat. Nebelungs have long bodies, wide-set green eyes, long and dense fur, and mild dispositions. The name Nebelung — apparently a portmanteau of the German word Nebel (''mist'' or ''fog''), and the name of a medieval Germanic saga, Nibelungenlied — is perhaps derived from the cat''s distinctive silky blue-grey coat and from the breed''s progenitors, who were named after the two major figures in the Nibelungenlied, the German warrior Siegfried and the Icelandic queen Brunhilde.
When it comes to the Nebelung, the operative word is long: long, graceful neck and body, long legs, long coat, and long tail. Slightly oval eyes are a vivid green color, or sometimes a yellow-green. Large, pointed ears sit atop a modified wedge-shaped head that is more pointed than rounded. The overall appearance is of a long, sturdy, well-muscled cat. The soft double coat feels fine and silky; it is a beautiful gray color and is tipped with silver. Males and, to a lesser extent, females have a ruff around the neck. The fur on the tail is longer than that on the body. Tufts of fur are found behind the ears and in-between the toes, and the hind legs sport pantaloons. The adult coat reaches its full development when the cat is approximately two years old. Life span of a Nebelung is 16+ years. A Nebelung weighs between 3.5 kg (7.11 lbs) for female and 6.5 kg (14.5 lbs) for male sterilized.');
INSERT INTO `catInfo` VALUES (53,'Napoleon/Minuet','The Napoleon cat[1] (also known as the Minuet) is a recent breed, categorized by The International Cat Association (TICA) as a domestic hybrid breed, "a breed developed from a deliberate cross between two existing domestic breeds, incorporating characteristics of both parental breeds into the new breed." [2] The two breeds from which make this cat are the Munchkin and the Persian. According to TICA’s official standard for the Minuet, these breeds represent the only permissible outcrosses one may use to create the Napoleon.[3] This includes the combinations Minuet × Minuet, Minuet × Munchkin, and Minuet × a member of the Persian breeds (including Persians, Himalayans and Exotic Shorthairs. Napoleons come in both long-haired and short-haired varieties.');
INSERT INTO `catInfo` VALUES (54,'Norwegian Forest cat','The Norwegian Forest cat (Norwegian: Norsk skogkatt or Norsk skaukatt) is a breed of domestic cat originating in Northern Europe[1]. This natural breed is adapted to a very cold climate, with a top coat of glossy, long, water-shedding hairs and a woolly undercoat for insulation. Although this is uncertain, the breed''s ancestors may have been a landrace of short-haired cats brought to Norway by the Vikings around 1000 AD, who may also have brought with them long-haired cats, like those ancestral to the modern Siberian and Turkish Angora breeds. During World War II, the breed became nearly extinct until efforts by the Norwegian Forest Cat Club helped the breed by creating an official breeding program. It was registered as a breed with the European Fédération Internationale Féline in the 1970s, when a local cat fancier, Carl-Fredrik Nordane, took notice of the breed and made efforts to register it. Currently, the Norwegian Forest breed is very popular in Norway, Sweden, Iceland and France.

It is a big, strong cat, similar to the Maine Coon breed, with long legs, a bushy tail and a sturdy body. The breed is very good at climbing, since they have strong claws. The lifespan is usually 14 to 16 years, though kidney and heart diseases have been reported in the breed. Specifically in this breed, complex rearrangements of glycogen branching enzyme (GBE1) can cause a perinatal hypoglycaemic collapse and a late-juvenile-onset neuromuscular degeneration in glycogen storage disease type IV');
INSERT INTO `catInfo` VALUES (55,'Ocicat','The Ocicat is an all-domestic breed of cat which resembles a wild cat but has no wild DNA in its gene pool. The breed is unusual in that it is spotted like a wild cat but has the temperament of a domestic animal. It is named for its resemblance to the Ocelot. The breed was established from Siamese and Abyssinian stock; later, American Shorthairs (silver tabbies) were added to the mix and gave the breed their silver color, bone structure and distinct markings.
There are twelve colors approved by most registries, including The Cat Fanciers'' Association, Inc. standard for the Ocicat breed: tawny, chocolate and cinnamon, their dilutes, blue, lavender and fawn, and all of them with silver: black silver (ebony silver), chocolate silver, cinnamon silver, blue silver, lavender silver and fawn silver. Ocicats have almond shaped eyes. They also have large, strong bodies, muscular legs with dark markings, and powerful, oval shaped paws. Their heads can be described as having a "wedge" shape that is longer than wide.[4] Their ears are tilted at a 45 degree angle. One of the most striking things about these cats is the dark contrasting spots. The body shape of the Ocicat is partway between the svelte Oriental and the sturdy American Shorthair. The breed''s large, well-muscled body gives an impression of power and strength, and is greater in weight than expected by appearance.');
INSERT INTO `catInfo` VALUES (56,'Ojos Azules','Cats with dark blue eyes were discovered in New Mexico among feral cat populations. The first cat, discovered in 1984, was a tortoiseshell named Cornflower. She was bred to males without the trait, which proved to be dominant, as all her kittens showed it. The breed was founded and named Ojos Azules, Spanish meaning ''Blue Eyes''.
The medium-sized Ojos Azules is known for its bluish eyes, which are large and round. The neck is arched. The tail is proportionate to the cat''s body. The head is somewhat triangular in inscribe. It has a slightly rounded forehead, and an angular muzzle. The nose has a slight break. The coat is short, fine, soft, silky, and shiny. The undercoat is not particularly developed but most are dense in color. All colors are allowed. White markings are common on most extremities (tip of the tail, muzzle, and paws). However, belly spots or chest spots are not acceptable, and are considered faults. Particolors have a white tail tip. Solid white coats are not desirable, as they cannot be distinguished from common white, blue-eyed cats. Note that white, blue-eyed Ojos Azules are not deaf like most common white, blue-eyed cats. In addition, other than cats of the Ojos Azules breed, only white or colorpoint cats can have blue eyes.');
INSERT INTO `catInfo` VALUES (57,'Oregon Rex','The Oregon Rex was one of several breeds of domestic cat with the rex coat variation, which in the mid-20th-century occurred from spontaneous genetic mutation.

After its acknowledgment as a separate breed, it enjoyed a short time of popularity among cat breeders in the United States. By now, due to crossbreeding with other Rex types, this breed seems to have merged with the other more popular Rex breeds like Devon Rex or Cornish Rex.
The typical curly coat was silky, short and tight, and featured no or only relatively short guard hair. The kemp was shorter than the German Rex''s or Cornish Rex''s and was fully developed, with a typical subapical swelling. Their minimal flexion made the kemp hairs longer than the undercoat. The number of hairs was normal, but the bristles were missing.

The head was wedge-shaped with a long bridge. The ears were large with smoothly rounded edges and were set high on the head, and the eyes were medium-sized with an oval shape.

The Oregon Rex''s body was of an elongated and tiny build, the tail was long, slim and peaked. The legs were long, gracile and slim, with tiny, round paws.');
INSERT INTO `catInfo` VALUES (58,'Oriental Bicolor','The Oriental Bicolour is any cat of Oriental type, either longhaired or shorthaired and in any pattern including colourpoint, which has white areas on its coat caused by the white spotting gene.
The Oriental Bicolour is a cat of Oriental type with a long, slender body and tapering whip-like tail. The triangular shape of the head is made of straight lines with a straight side profile and large, wide-set ears. The eyes are green, except in the colourpoint varieties which have blue eyes. The coat on the shorthaired variety is sleek, close-lying and glossy, while that of the longhair is fine and silky, lying flat to the body with no thick undercoat and forming a plume on the tail. The full range of colours seen in Siamese and Orientals is permitted, however a defining feature of breed is that they always have white spotting. In a cat of show quality this should extend to cover at least one third of the body and the distribution may be random and quirky like splashed paint. There is always a greater distribution of white on the cat''s underside and legs in comparison with its back. This patterning is caused by the dominant white spotting gene, which is symbolized with the letter S.');
INSERT INTO `catInfo` VALUES (59,'Oriental Shorthair','The Oriental Shorthair is a breed of domestic cat that is closely related to the Siamese. It maintains the modern Siamese head and body type but appears in a wide range of coat colors and patterns. Like the Siamese, Orientals have almond-shaped eyes, a triangular head shape, large ears, and an elongated, slender, and muscular body. Their personalities are also very similar. Orientals are social, intelligent, and many are rather vocal. They often remain playful into adulthood, with many enjoying playing fetch. Despite their slender appearance, they are athletic and can leap into high places. They prefer to live in pairs or groups and also seek human interaction. Unlike the breed''s blue-eyed forebear, Orientals are usually green-eyed.[1] The Oriental Longhair differs only with respect to coat length.

While the breed''s genetic roots are ultimately in Thailand, it was formally developed principally in the US. The Oriental Shorthair was accepted in 1977 by the Cat Fanciers'' Association for championship competition. Since 1997, it has also received recognition from the GCCF and various other cat breeding organizations. The breed is among the most popular among CFA members.');
INSERT INTO `catInfo` VALUES (60,'Oriental Longhair','The Oriental Longhair is a breed of domestic cat. It is closely related to the Oriental Shorthair.

The Oriental Longhair is analogous to the CFA Balinese and Javanese, and the TICA Oriental Longhair breeds in the United States. With no globally recognized naming convention, other cat fanciers may refer to this type as Foreign Longhair or Mandarin. It was formerly known as the British Angora before being renamed in 2002 by British cat fanciers in order to avoid confusion with the Turkish Angora.');
CREATE TABLE IF NOT EXISTS `android_metadata` (
	`locale`	TEXT
);
INSERT INTO `android_metadata` VALUES ('en_US');
COMMIT;
